version: "3.8"
services:
  loki:
    image: grafana/loki:3.1.0 # tail looses logs
#    image: grafana/loki:2.9.0 # no issues with tailing
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  fluent-bit:
    image: fluent/fluent-bit:3.1.3
    depends_on:
      - loki
    volumes:
      - ./:/var/logs
      - ./fluent-bit.yml:/fluent-bit/etc/fluent-bit.yml
    command: -c /fluent-bit/etc/fluent-bit.yml

